name: umshare
description: A new flutter plugin project.
version: 0.2.0
# author:
homepage: https://github.com/1035901787/flutter-umshare

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.arno.umshare
        pluginClass: UmsharePlugin
      ios:
        pluginClass: UmsharePlugin
